CREATE DATABASE bdPartidoPTC

USE bdPartidoPTC

SELECT * FROM FiliadosPTC

SELECT COUNT (numero_da_inscricao ) AS 'Número inscrição' FROM FiliadosPTC 

 SELECT NOME_DO_FILIADO FROM FiliadosPTC
 WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'--1

 SELECT NOME_DO_FILIADO FROM FiliadosPTC
 WHERE NOME_DO_FILIADO LIKE '%SEBASTIAO'--2

 SELECT NOME_DO_FILIADO FROM FiliadosPTC
 WHERE NOME_DO_FILIADO LIKE 'OS%'--3

 SELECT NOME_DO_FILIADO FROM FiliadosPTC
 WHERE NOME_DO_MUNICIPIO LIKE '%LIX'--4

 SELECT NOME_DO_FILIADO FROM FiliadosPTC
 WHERE NOME_DO_MUNICIPIO LIKE 'INHAMBUPE'--5

 SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
 WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%' --6

 SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
 WHERE NOME_DO_MUNICIPIO LIKE 'E%'--7

 SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
 WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'--8

 SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
 WHERE NOME_DO_MUNICIPIO LIKE '%DE%'--9

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', DATA_DA_FILIACAO AS 'Data da Filiação' FROM FiliadosPTC
 WHERE DATA_DA_FILIACAO BETWEEN '01-01-1990' AND '01-01-2000'--10


 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', DATA_DA_FILIACAO AS 'Data da Filiação' FROM FiliadosPTC
 WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010 ' AND '01/03/2010'--10
